<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class EventBase  {
		private $_id;
		private $_id_Competitor1;
		private $_id_Competitor2;
		private $_score_Competitor1;
		private $_score_Competitor2;
		private $_date;
		private $_queryBuilder;

		public function __construct($id = '', $id_Competitor1 = '', $id_Competitor2 = '', $score_Competitor1 = '', $score_Competitor2 = '', $date = ''){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "id_Competitor1" => $id_Competitor1, "id_Competitor2" => $id_Competitor2, "score_Competitor1" => $score_Competitor1, "score_Competitor2" => $score_Competitor2, "date" => $date));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getId_Competitor1() {
			return $this->_id_Competitor1;
		}
		public function getId_Competitor2() {
			return $this->_id_Competitor2;
		}
		public function getScore_Competitor1() {
			return $this->_score_Competitor1;
		}
		public function getScore_Competitor2() {
			return $this->_score_Competitor2;
		}
		public function getDate() {
			return $this->_date;
		}

		public function getCompetitor1($repository) {
			$result = $repository->getById($this->_id_Competitor1);
			return $result;
		}
		public function getCompetitor2($repository) {
			$result = $repository->getById($this->_id_Competitor2);
			return $result;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["id_Competitor1"]))
				$this->_id_Competitor1 = $properties["id_Competitor1"];
			if(!empty($properties["id_Competitor2"]))
				$this->_id_Competitor2 = $properties["id_Competitor2"];
			if(!empty($properties["score_Competitor1"]))
				$this->_score_Competitor1 = $properties["score_Competitor1"];
			if(!empty($properties["score_Competitor2"]))
				$this->_score_Competitor2 = $properties["score_Competitor2"];
			if(!empty($properties["date"]))
				$this->_date = $properties["date"];
		}
	}
